### ISSUE TITLE
Update Jedi Version

### ISSUE THREAD

**Issue by agoose77** [jupyter-xeus/xeus-python#364] opened 2020-12-04 14:13 UTC
Hi all,

I noticed that completion wasn't working for me in JupyterLab 2.2.9, using the default Python kernel. I removed `xeus-python` and updated my dependencies with `poetry update` and observed that it fixed the problem. It seems that the upper bound of the `jedi` dependency does not work with JLab 2.2.9, Python 3.8.5 (at least, anecdotally). I don't know where the issue is exactly, but upgrading `jedi` by removing `xeus-python` seems to fix the issue.

Would it be possible to support newer versions of `jedi` in the hope that this fixes things?

**Comment by martinRenou** [comment] 2020-12-04 14:24
Hi,

No problem updating `jedi`, hopefully, everything would still work properly without code change.

But are you sure the issue is related to the jedi version? I recall seeing issues on IPython from people complaining that when jedi was installed (simply installed) there were multiple issues on the completion. Jedi is an optional dependency on IPython IIRC, and when it's installed it messes everything up.

**Comment by agoose77** [comment] 2020-12-04 14:55
I think so - I realise that I didn't do a rigorous test. I had jedi installed in both cases, but the older version seemed not to work for me. It might work properly under the `xeus-python` kernel; I only tested the default kernel :). I should really write a PR here, though, rather than just complain :)

**Comment by martinRenou** [comment] 2020-12-04 15:02
> I had jedi installed in both cases, but the older version seemed not to work for me

Ok :) Jedi seems to move fast, I thought we were already using the latest.

> I should really write a PR here, though, rather than just complain :)

Ahah no worries. I do the same.
Note that there is no requirement file or something in this repo, we just put the jedi version as information in the README, and the conda-forge package contains the truth of what will be installed.

**Comment by SylvainCorlay** [comment] 2020-12-13 15:38
This should be fixed in the latest releases!

**Closed by SylvainCorlay** 2020-12-13 15:38 UTC
