### ISSUE TITLE
Add xeus-python in existing python environment ?

### ISSUE THREAD

**Issue by rquintino** [jupyter-xeus/xeus-python#206] opened 2020-03-09 09:28 UTC
I wanted to give the new jupyter lab debugger a try (https://github.com/jupyterlab/debugger), from what I've read requires, xeus-python. 

It would be great to just plug this onto our existing python envs, docker based, very often without conda/miniconda. Anyone knows if this is possible? 

Thanks!

**Comment by JohanMabille** [comment] 2020-03-13 18:40
We are working on a [wheel](https://github.com/jupyter-xeus/xeus-python-wheel) for xeus-python. It should be available soon, stay tuned!

**Comment by SylvainCorlay** [comment] 2020-03-28 12:44
Hi @rquintino we now have an experimental wheel up on PyPI - linux 64 only.

**Comment by SylvainCorlay** [comment] 2020-03-28 12:47
Closing as a duplicate of #181.

**Closed by SylvainCorlay** 2020-03-28 12:47 UTC
