### ISSUE TITLE
How to install without using conda

### ISSUE THREAD

**Issue by chespinoza** [jupyter-xeus/xeus-python#205] opened 2020-03-08 18:29 UTC
I'm using pipenv and poetry in my machine and I'm not interested in installing conda, is there a way to use this kernel without conda?

Thanks.

**Comment by SylvainCorlay** [comment] 2020-03-08 18:43
We are working on a creating a wheel for PyPI at https://github.com/jupyter-xeus/xeus-python-wheel but we have not published them yet.

We still have some issues to solve before publishing it. If you have experience with this, help would be very welcome.

Note that we will always recommend using a package manager and not PyPI. Wheels don't support binary relocation.

**Comment by SylvainCorlay** [comment] 2020-03-08 18:52
Closing as a duplicate of #181.

**Closed by SylvainCorlay** 2020-03-08 18:52 UTC
