### ISSUE TITLE
No plots being generated using matplotlib/seaborn

### ISSUE THREAD

**Issue by arush1947** [jupyter-xeus/xeus-python#305] opened 2020-07-13 20:12 UTC
I am unable to plot graphs using seaborn and matplotlib. It appears others are experiencing this issue as well.

This might be related to magics like "%motplotlib inline" not being supported by the kernel currently. There seems to be general compatibility issue with matplotlib(3.2.2)/seaborn(0.10.1)
Your help is much appreciated :)

[Notebooks with error.zip](https://github.com/jupyter-xeus/xeus-python/files/4914834/Notebooks.with.error.zip)

**Comment by martinRenou** [comment] 2020-07-15 06:58
xeus-python does not support Matplotlib yet, as IPython has a lot of matplotlib custom logic (and the matplotlib Jupyter back-ends simply assume IPython is being used).

Closing as duplicate of #224.

**Closed by martinRenou** 2020-07-15 06:58 UTC

**Comment by arush1947** [comment] 2020-07-15 15:16
Thank you for the update Martin. Are there any plans to extend support in xeus for matplotlib or ipython?


Sent via the Samsung Galaxy S20+ 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by martinRenou** [comment] 2020-07-15 15:18
There are plans indeed, there are some discussions happening between Matplotlib/IPython/xeus-python developpers. But I cannot give you any time frame though.
