### ISSUE TITLE
Matplotlib and %matplotlib inline not working in xeus-python

### ISSUE THREAD

**Issue by pratikchhapolika** [jupyter-xeus/xeus-python#309] opened 2020-07-20 20:50 UTC
I am writing the below code:

```
def plot_distribution(inp):
    
    plt.figure()
    
    ax = sns.distplot(inp)
    
    plt.axvline(np.mean(inp), color="k", linestyle="dashed", linewidth=5)
    
    _, max_ = plt.ylim()
    plt.text(
        inp.mean() + inp.mean() / 10,
        max_ - max_ / 10,
        "Mean: {:.2f}".format(inp.mean()),
    )
    return plt.figure
```

`plot_distribution(df['var'])`

**Error:**

**---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
In  [28]:
Line 1:     plot_distribution(final_table4['ci_share'])

In  [27]:
Line 3:     plt.figure()

File C:\Users\**\Anaconda3\envs\jupyterlab-debugger2\lib\site-packages\matplotlib\pyplot.py, in figure:
Line 676:   **kwargs)

File C:\Users\**\Anaconda3\envs\jupyterlab-debugger2\lib\site-packages\matplotlib\pyplot.py, in new_figure_manager:
Line 298:   return _backend_mod.new_figure_manager(*args, **kwargs)

File C:\Users\**\Anaconda3\envs\jupyterlab-debugger2\lib\site-packages\matplotlib\backend_bases.py, in new_figure_manager:
Line 3490:  return cls.new_figure_manager_given_figure(num, fig)

File C:\Users\**\Anaconda3\envs\jupyterlab-debugger2\lib\site-packages\matplotlib\backends\_backend_tk.py, in new_figure_manager_given_figure:
Line 859:   window = tk.Tk(className="matplotlib")

File C:\Users\**\**\envs\jupyterlab-debugger2\lib\tkinter\__init__.py, in __init__:
Line 2018:  baseName = os.path.basename(sys.argv[0])

IndexError: list index out of range
---------------------------------------------------------------------------**

**Comment by martinRenou** [comment] 2020-07-21 07:19
The cause of the error is interesting:
```
Line 2018: baseName = os.path.basename(sys.argv[0])

IndexError: list index out of range
```

We might want to check what ipykernel has there that we have not.

**Comment by SylvainCorlay** [comment] 2020-07-21 09:43
There was another issue with sys.argv not being populated in the xpython executable.

I think that we should set the program name with `Py_SetProgramName`.

**Comment by pratikchhapolika** [comment] 2020-07-21 10:04
So, what is the solution. It's so dsappointing that for `debugger` we need `xeus-python` and for plotting figures we agin to move to normal python.  When I present my project I can't really move from one kernel to another. The audience will laugh. xD

**Comment by SylvainCorlay** [comment] 2020-07-22 07:34
>  The audience will laugh. xD

I think this is getting a bit out of bound. Please remain courteous. Jupyter developers are putting an incredible amount of work that you can use for free. Please remain courteous when engaging with the community. Let me point you to the Jupyter code of conduct: https://github.com/jupyter/governance/blob/master/conduct/code_of_conduct.md

I locked the conversation and I am closing the issue as a duplicate of the other questions on the support of the matplotlib magic.

**Closed by SylvainCorlay** 2020-07-22 07:34 UTC
