### ISSUE TITLE
Xeus-python should not advertise debugging capabilities if ptvsd is not installed

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-xeus/xeus-python#180] opened 2019-11-20 19:18 UTC
At the moment xeus-python always returns "true" for the debugger key of the kernel info request.

Should we return "false" if ptvsd ia not available?

**Comment by martinRenou** [comment] 2019-11-21 07:21
Don't we want `ptvsd` to be a hard dependency? So the user does't need to install it himself?

**Comment by SylvainCorlay** [comment] 2019-11-21 07:34
I don't know.

**Comment by SylvainCorlay** [comment] 2019-11-21 07:35
It may be harder to push for xpython to be the default kernel if you have to pull ptvsd...

**Comment by martinRenou** [comment] 2019-11-21 07:36
Why? `ptvsd` is a small Python package, just like other Python dependencies we already have

**Comment by JohanMabille** [comment] 2019-11-21 07:59
Also we may want to switch to another debugger at some point. Having ptvsd as a hard dependency would make such a change backward incompatible while I am not sure it would be the case for an optional dependency.

**Comment by martinRenou** [comment] 2019-11-21 08:02
The debug adapter protocol fits our needs in terms of language agnosticism for Jupyter. I am not sure it would be a good idea to come up with our own protocol.

**Comment by JohanMabille** [comment] 2019-11-21 08:09
I didn't mean that we would change the protocol, only that we could change the debugger implementation. That could be developping or own implementation of the protocol on top of pydev to fix the problems of ptvsd specific to the interactive mode.

**Comment by martinRenou** [comment] 2019-11-21 08:15
If we have issues specific to the interactive mode, it would be preferable to try and contribute to pydevdebugger before considering implementing our own debugger.

**Comment by JohanMabille** [comment] 2019-11-21 08:22
The problem is not in pydev but in ptvsd, see https://github.com/microsoft/ptvsd/issues/201

**Comment by martinRenou** [comment] 2019-11-21 08:26
Ok sorry, I did not understand your message. I thought it was a pydev debugger issue.

Well, then I'm even more convinced that ptvsd could be a hard dependency. This way, if we need to switch to something else, users will just need to update xeus-python with conda. And they won't need to bother installing another library by hand to make it work again.

I am not sure I understand why you say changing one dependency would be a backward-incompatible change?

**Comment by JohanMabille** [comment] 2019-11-21 08:30
No problem, I realize that my previous statements are not that clear. So to be more accurate we may want to:
- provide our own implementation of the Debug Adapter Protocol on top of pydev
- switch to another debugger and provide our own implementation of the Debug Adapter Protocol if this debugger doe snot provide one.

Regarding the dependencies, indeed I may be wrong since ptvsd is never exposed in the API.

**Comment by afshin** [comment] 2019-11-29 12:11
I think the contract with clients is all about the implementation of the debug adapter protocol in addition to the few things we wanted to support in a user experience (*i.e.* telling the client debugging is available via a flag and giving the client a way to poll the current variable state even when not in a breakpoint).

Since the contract is completely about the public facing protocol, the addition of a dependency on `ptvsd` seems like an implementation detail to me. Shipping with it as a hard dependency seems better than not offering debugging services for users who don't have it.

**Comment by SylvainCorlay** [comment] 2019-12-27 12:45
I am ok with adding ptvsd as a dependency to xeus-python for now.

**Comment by edurenye** [comment] 2020-05-06 21:32
`ptvsd` is being moved to `debugpy`, maybe we should move too before setting `ptvsd` as a hard dependency and directly do so with `debugpy`.

**Comment by SylvainCorlay** [comment] 2020-05-06 21:40
Absolutely we should do this at some point.

**Comment by JohanMabille** [comment] 2020-08-10 08:15
Closing this since ptvsd has been added as a dependency of `xeus-python`. Let's open a new issue for tracking the switch to debugpy.

**Closed by JohanMabille** 2020-08-10 08:15 UTC
